### ISSUE TITLE
Error: LoadManager class not created

### ISSUE THREAD

**Issue by yehonadav** [roadmanfong/zustand-persist#2]
![image](https://user-images.githubusercontent.com/35917238/93327645-4a298400-f823-11ea-9eed-cb89b96e8bef.png)

this error pops up when there are 0 stores imported in the app: 
![image](https://user-images.githubusercontent.com/35917238/93327780-8230c700-f823-11ea-8b17-13994a347d0e.png)

i would suggest creating a default loadManager, just so the app does't break if let's say i have a build that doest not need persistent.
Possibly get rid of the PersistGate would be even better if possible

**Comment by yehonadav** [comment]
if i import the configured persist my app crash completely but no error is presented:
![image](https://user-images.githubusercontent.com/35917238/93328645-ab058c00-f824-11ea-86b3-dfb3918bdfc2.png)

![image](https://user-images.githubusercontent.com/35917238/93328625-a345e780-f824-11ea-818e-7c97420139e0.png)

**Comment by yehonadav** [comment]
for now just importing an empty store solves this
![image](https://user-images.githubusercontent.com/35917238/93329269-9aa1e100-f825-11ea-8729-b7c0c793ecb1.png)

![image](https://user-images.githubusercontent.com/35917238/93329207-85c54d80-f825-11ea-87e9-656f6bef283b.png)

**Comment by roadmanfong** [comment]
I'll take a look later
