### ISSUE TITLE
Usage with next.js

### ISSUE THREAD

**Issue by pzi** [roadmanfong/zustand-persist#3]
Hi Steven,

I am trying to set up zustand with zustand-persist and I am running into issues when running it with next.js. Most notably, during the build when nextjs builds out the static pages and `localStorage` is not defined.

Secondly, the `PersistGate` doesn't seem to get lifted after first load, only after a page refresh. Even though all data has been loaded and initialised.

Looks like the reconciliation will need some checks if the DOM/storage is actually available and initialise the default state differently. i.e. something like `const isRunningInBrowser = () => typeof window !== "undefined";`

Somewhat similar to what has been done here: https://github.com/pmndrs/zustand/issues/76#issuecomment-670367631

Any thoughts/ideas on this?

Cheers

**Comment by roadmanfong** [comment]
I'm not familiar with next.js
did you try 
https://github.com/vercel/next.js/discussions/15687#discussioncomment-45319

idea is create a `noopStorage` if this is `isRunningInBrowser` 

please let me know if it works, thanks
