### ISSUE TITLE
Note new visitors that this library is no longer maintained

### ISSUE THREAD

**Issue by bekazandukeli** [roadmanfong/zustand-persist#30]
As I have noticed this library is not maintained anymore and Zustand added built-in middleware for persistors.

I think this GitHub page should notify the abovementioned developments to new users to avoid further confusion.

Best regards,
Beka

**Comment by smallsaucepan** [comment]
Thanks for the suggestion @bekazandukeli.

@roadmanfong this your repo though. Any objections to placing a notice at the top of the readme? I'm happy to do the work.

**Comment by smallsaucepan** [comment]
Message added to top of readme
